// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $Cementation from "./islands/Cementation.tsx";
import * as $Countersinking from "./islands/Countersinking.tsx";
import * as $FeaturedProducts from "./islands/FeaturedProducts.tsx";
import * as $ForggotPassword from "./islands/ForggotPassword.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_HamburguerMenu from "./islands/Header/HamburguerMenu.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $InitialInspection from "./islands/InitialInspection.tsx";
import * as $LanguageButton from "./islands/LanguageButton.tsx";
import * as $Login from "./islands/Login.tsx";
import * as $MenuHamburguer from "./islands/MenuHamburguer.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $ProductDetails from "./islands/ProductDetails.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $ProductList from "./islands/ProductList.tsx";
import * as $ProductSearch from "./islands/ProductSearch.tsx";
import * as $Register from "./islands/Register.tsx";
import * as $Scraping from "./islands/Scraping.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $SearchResult from "./islands/SearchResult.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $TesteWaterJet from "./islands/TesteWaterJet.tsx";
import * as $User from "./islands/User.tsx";
import * as $WaterJetProductSearch from "./islands/WaterJetProductSearch.tsx";
import * as $WaterJetProducts from "./islands/WaterJetProducts.tsx";
import * as $WhatsAppButon from "./islands/WhatsAppButon.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/Cementation.tsx": $Cementation,
    "./islands/Countersinking.tsx": $Countersinking,
    "./islands/FeaturedProducts.tsx": $FeaturedProducts,
    "./islands/ForggotPassword.tsx": $ForggotPassword,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/HamburguerMenu.tsx": $Header_HamburguerMenu,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/InitialInspection.tsx": $InitialInspection,
    "./islands/LanguageButton.tsx": $LanguageButton,
    "./islands/Login.tsx": $Login,
    "./islands/MenuHamburguer.tsx": $MenuHamburguer,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/ProductDetails.tsx": $ProductDetails,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/ProductList.tsx": $ProductList,
    "./islands/ProductSearch.tsx": $ProductSearch,
    "./islands/Register.tsx": $Register,
    "./islands/Scraping.tsx": $Scraping,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/SearchResult.tsx": $SearchResult,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/TesteWaterJet.tsx": $TesteWaterJet,
    "./islands/User.tsx": $User,
    "./islands/WaterJetProductSearch.tsx": $WaterJetProductSearch,
    "./islands/WaterJetProducts.tsx": $WaterJetProducts,
    "./islands/WhatsAppButon.tsx": $WhatsAppButon,
    "./islands/WishlistButton.tsx": $WishlistButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
