// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $$0 from "./islands/AddToCartButton/shopify.tsx";
import * as $$1 from "./islands/AddToCartButton/vnda.tsx";
import * as $$2 from "./islands/AddToCartButton/vtex.tsx";
import * as $$3 from "./islands/AddToCartButton/wake.tsx";
import * as $$4 from "./islands/FeaturedProducts.tsx";
import * as $$5 from "./islands/Header/Buttons.tsx";
import * as $$6 from "./islands/Header/Cart/shopify.tsx";
import * as $$7 from "./islands/Header/Cart/vnda.tsx";
import * as $$8 from "./islands/Header/Cart/vtex.tsx";
import * as $$9 from "./islands/Header/Cart/wake.tsx";
import * as $$10 from "./islands/Header/Drawers.tsx";
import * as $$11 from "./islands/Header/HamburguerMenu.tsx";
import * as $$12 from "./islands/Header/Searchbar.tsx";
import * as $$13 from "./islands/LanguageButton.tsx";
import * as $$14 from "./islands/Login.tsx";
import * as $$15 from "./islands/MenuHamburguer.tsx";
import * as $$16 from "./islands/Newsletter.tsx";
import * as $$17 from "./islands/OutOfStock.tsx";
import * as $$18 from "./islands/ProductDetails.tsx";
import * as $$19 from "./islands/ProductImageZoom.tsx";
import * as $$20 from "./islands/ProductList.tsx";
import * as $$21 from "./islands/Register.tsx";
import * as $$22 from "./islands/SearchControls.tsx";
import * as $$23 from "./islands/ShippingSimulation.tsx";
import * as $$24 from "./islands/SliderJS.tsx";
import * as $$25 from "./islands/WhatsAppButon.tsx";
import * as $$26 from "./islands/WishlistButton.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
  },
  islands: {
    "./islands/AddToCartButton/shopify.tsx": $$0,
    "./islands/AddToCartButton/vnda.tsx": $$1,
    "./islands/AddToCartButton/vtex.tsx": $$2,
    "./islands/AddToCartButton/wake.tsx": $$3,
    "./islands/FeaturedProducts.tsx": $$4,
    "./islands/Header/Buttons.tsx": $$5,
    "./islands/Header/Cart/shopify.tsx": $$6,
    "./islands/Header/Cart/vnda.tsx": $$7,
    "./islands/Header/Cart/vtex.tsx": $$8,
    "./islands/Header/Cart/wake.tsx": $$9,
    "./islands/Header/Drawers.tsx": $$10,
    "./islands/Header/HamburguerMenu.tsx": $$11,
    "./islands/Header/Searchbar.tsx": $$12,
    "./islands/LanguageButton.tsx": $$13,
    "./islands/Login.tsx": $$14,
    "./islands/MenuHamburguer.tsx": $$15,
    "./islands/Newsletter.tsx": $$16,
    "./islands/OutOfStock.tsx": $$17,
    "./islands/ProductDetails.tsx": $$18,
    "./islands/ProductImageZoom.tsx": $$19,
    "./islands/ProductList.tsx": $$20,
    "./islands/Register.tsx": $$21,
    "./islands/SearchControls.tsx": $$22,
    "./islands/ShippingSimulation.tsx": $$23,
    "./islands/SliderJS.tsx": $$24,
    "./islands/WhatsAppButon.tsx": $$25,
    "./islands/WishlistButton.tsx": $$26,
  },
  baseUrl: import.meta.url,
};

export default manifest;
